sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
  - '4'
  - '3'
  - '2'
  - '1'
before_install: "npm install -g npm"
script: "npm run-script travis"
after_success: "<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js"
